ALTER TABLE [dbo].[TB_TMP_CARGA_LOG] DROP CONSTRAINT [DF_TB_TMP_CARGA_LOG_ID_CARGA]
GO

/****** Object:  Table [dbo].[TB_TMP_CARGA_LOG]    Script Date: 14/04/2021 10:02:16 ******/
DROP TABLE [dbo].[TB_TMP_CARGA_LOG]
GO

/****** Object:  Table [dbo].[TB_TMP_CARGA_LOG]    Script Date: 14/04/2021 10:02:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_TMP_CARGA_LOG](
	[ID_CARGA] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[DESCRICAO_CARGA] [varchar](80) NOT NULL,
	[STATUS_CARGA] [char](1) NULL,
	[DETALHE_CARGA] [varchar](350) NULL,
	[DT_CARGA] [datetime] NOT NULL,
	[QT_REGISTROS] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_TMP_CARGA_LOG] ADD  CONSTRAINT [DF_TB_TMP_CARGA_LOG_ID_CARGA]  DEFAULT (newid()) FOR [ID_CARGA]
GO

